### ISSUE TITLE
Nothing to publish for tag[config]

### ISSUE THREAD

**Issue by GSto** [spekkionu/laravel-assetcachebuster#10]
Followed instructions to install package on an existing application using Laravel 5.2.29. 

When Attempting to run this command from the documentation: 
`php artisan vendor:publish --provider=Spekkionu\Assetcachebuster\AssetcachebusterServiceProvider --tag=config`

I receive the following error message: 

`Nothing to publish for tag [config].`

**Comment by spekkionu** [comment]
Try putting quotes around the provider.

```
php artisan vendor:publish --provider="Spekkionu\Assetcachebuster\AssetcachebusterServiceProvider" -tag=config
```

This needs to be done in some terminals.
