### ISSUE TITLE
Hash file names.

### ISSUE THREAD

**Issue by almamundinajpuri** [spekkionu/laravel-assetcachebuster#7]
Hello,
Is there anyway to hash file names too? For example, if I've a style.css, I could get **96c8a2176fd1f379e91e512e1418b94e.css** ?

Regards

**Comment by spekkionu** [comment]
This would require a separate hash for each file and is beyond what I need for this package.

Try using something like [gulp-rev](https://www.npmjs.com/package/gulp-rev) or [grunt-rev](https://www.npmjs.com/package/grunt-rev) to accomplish what you want.
