### ISSUE TITLE
Request: Set hash in .env file

### ISSUE THREAD

**Issue by LukasMa** [spekkionu/laravel-assetcachebuster#8]
Everytime I push to my webserver, I also execute the "php artisan assetcachebuster:generate" command to invalidate my cash. Problem: This will set the key/hash in the config file and crash my git, because I can't pull in the changes. Git want's to get the changes made in the config file (new hash) commited before pulling. So I need to hard reset my git repo on my webserver everytime I want to pull changes. That's not a good solution.

Is it possible to make the "php artisan assetcachebuster:generate" command generate the hash in the .env file?

**Comment by spekkionu** [comment]
This would be possible by implementing Spekkionu\Assetcachebuster\Writer\WriterInterface with a class that writes to the .env file instead.
